### PR TITLE
Added a driver circuit meant to interface with the 1.44' EPD.

### PR DESCRIPTION
**Pull request by Millerj1994**

### CODE REVIEW

**Comment by zbears** [comment]
Summary of required changes:
1. Components C1, R1, and C11 need values
2. All required components must be added to the order sheet to verify footprints
3. Decision must be made as to if we can handle 0402 components instead of 0603
4. Overlapping labels in the circuit diagram must be moved for diagram clarity
5. Temperature sensor must be added for proper refresh rate. See note 2 on p 12 of Pervasive Displays datasheet
6. Naming nets as "Connect to timing controller SPI" has linked all those pins together. These are distinct pins in the SPI interface and must be named separately to avoid linking nets.
7. Your VCC/VDD net has label leading off but no pin text.
8. You have added all net labels to the net layer (91). It should be moved to the info layer (97). This is an option in the top menu when adding text. 
9. Your border pin on the bottom pin is mislabeled as "Connect to timing controller GPIO"
10. You have neglected to add the MOSFETS and the Diode included in the datasheet. Without them, we will have difficulty powering down the display.
11. You didn't put in the MOS power switch as suggested on the VDD pin by the datasheet to prevent leakage current. This is highly important for our low-power application.

**Comment by Millerj1994** [comment]
On 6., those are just text nodes, so i think its fine? I don't believe they're linked together, since I didnt assign the text to the net

**Comment by zbears** [comment]
Okay as long as they're moved to the text layer

**Comment by Millerj1994** [comment]
Wait, I also don't think we need 5. We're doing multiple writes to the EPD in order to get darker colors, and also we don't really care about write speed? Plus, how would we use the temperature sensor data anyway?

**Comment by Millerj1994** [comment]
How do I add pin text (7.)?

**Comment by Millerj1994** [comment]
Went to do 11 and 12, couldnt find the libs for the devices. Where can I find 2N7002KW?

**Comment by Millerj1994** [comment]
Anyway, solved about half of what you posted- waiting on responses to the other questions. Will repush in just a sec.

**Comment by zbears** [comment]
For 5, I was just concerned that it would affect the refresh rate on a pixel by pixel basis. If you think we're fine without it, I'll trust you on that. For 7 to add that text, use the label tool to place the net name on the branch then use the name tool to rename the mesh. For 11 and 12, make a custom part based off of the footprint of a similar part. It frequently happens that Eagle doesn't have the perfect parts. You just have to make due.

**Comment by Millerj1994** [comment]
@zbears Just updated this. Couldn't figure out what you meant by #7- also couldn't figure out how to successfully generate a custom part- however, I used one with a similar footprint.

**Comment by zbears** [comment]
Looks good. I'll take your word for the footprints and lack of thermometer.

**Pull request merged**
