### PR TITLE
Integrated EPD driver to main schematic.

### PR DESCRIPTION
**Pull request by Millerj1994**
Check out old PR for checking details.

### CODE REVIEW

**Comment by Millerj1994** [comment]
PLEASE

**Comment by Millerj1994** [comment]
@zbears @martelagelo @Negatu

**Comment by zbears** [comment]
None of your pins appear to be connected... Am I missing something?

**Comment by Millerj1994** [comment]
They should be? Heres what it looks like:
screen shot 2015-10-14 at 6 15 27 pm

**Comment by zbears** [comment]
Are you sure that version is attached to the pull request? Can you do a quick git status? Also is there logic behind your pin selections?

**Comment by Millerj1994** [comment]
Sorry for the slow response on this- it seems like I hadnt updated correctly, although the right circuit should now be up.

**Comment by Millerj1994** [comment]
err i was about to answer your questions hahaha

**Comment by Millerj1994** [comment]
damn dood agressive

**Comment by zbears** [comment]
forgot about my comments. I assume you were logical with your pin choice?

**Comment by Millerj1994** [comment]
yep- the old PR has a full explanation

**Comment by zbears** [comment]
sounds good to me

**Pull request merged**
