### PR TITLE
Merged the EPD driver circuit into the main schematic.

### PR DESCRIPTION
**Pull request by Millerj1994**

### CODE REVIEW

**Comment by zbears** [comment]
You're going to have to rename all your ground nets GND. It doesn't appear that they're connected. Also, are you sure you are using all the proper pins on the BLE113? I looks to me like your pin selection is pretty arbitrary. I'm not going to be able to take another chance to look at this before I leave so get Michael to check it out after these changes are verified.

**Comment by Millerj1994** [comment]
@zbears incorporated your feedback. Can @martelagelo review?

**Comment by Millerj1994** [comment]
@martelagelo can i get  review?

**Comment by Millerj1994** [comment]
[4P015-00_01_G2_Aurora+Ma_COG+Driver+Interface+Timing_for_small+size_20150216.pdf](https://github.com/zbears/MedStat/files/10127/4P015-00_01_G2_Aurora.Ma_COG.Driver.Interface.Timing_for_small.size_20150216.pdf)

You'll need to cross check this

**Comment by Millerj1994** [comment]
With this http://www.mouser.com/catalog/specsheets/Bluegiga_Technologies_BLE113_Datasheet.pdf

**Comment by Millerj1994** [comment]
Particularly with hardware config <usart channel="0" mode="spi_master" alternate="1" ...

screen shot 2015-10-08 at 10 38 05 am

**Comment by Millerj1994** [comment]
PLEASE FOR THE LOVE OF GOD

**Comment by Millerj1994** [comment]
WHY HAS NO ONE REVIEWED THIS

**Pull request closed without merging**
